### ISSUE TITLE
¿Bug? samplesPerFrq is fixed to 256 on output file

### ISSUE THREAD

**Issue by clbustos** [titinko/frq0003gen#1]
Third argument of frq0003 is the sample size, and is used to calculate the numbers of frames to report, but in line: 
https://github.com/titinko/frq0003gen/blob/8ae8209d5959c1ee2b6ff02dcf2f34cde4c55e5b/src/frq0003gen.cpp#L128

is fixed to 256. It is correct or should be fixed?

**Comment by titinko** [comment]
Right now the program only supports 256.  I put the parameter in with the expectation that it could be enhanced to support other sample rates in the future.

**Comment by clbustos** [comment]
Oh, ok. I understand
