### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ghost** [titinko/frq0003gen#2]
Hello
Could you tell me how to batch processing wav files on a folder by this tool?
I need some helps.

**Comment by titinko** [comment]
Hello,
You can use this tool by downloading the UTSU program.  If you open a voicebank and right-click on the "frq" column header, you will be able to regenerate all .frq files for the voicebank. 
<img width="925" alt="Screenshot 2024-03-20 at 12 12 31 PM" src="https://github.com/titinko/frq0003gen/assets/6768387/153361a1-9da8-4b56-bf7e-4649b61fce4e">

**Comment by ghost** [comment]
> Hello, You can use this tool by downloading the UTSU program. If you open a voicebank and right-click on the "frq" column header, you will be able to regenerate all .frq files for the voicebank. <img alt="Screenshot 2024-03-20 at 12 12 31 PM" width="925" src="https://private-user-images.githubusercontent.com/6768387/314641404-153361a1-9da8-4b56-bf7e-4649b61fce4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTczNTMsIm5iZiI6MTcxMTAxNzA1MywicGF0aCI6Ii82NzY4Mzg3LzMxNDY0MTQwNC0xNTMzNjFhMS05ZGE4LTRiNTYtYmY3ZS00NjQ5YjYxZmNlNGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjFUMTAzMDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzM4YzBmYzlkNzVhOGQyODkxNjdlMmRjMzk0N2MxZDIxMzcyNTc1NzZkY2JiNDEwZjhhYWIwOWU4MDIyZTdlOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1zBv9hQ_25bEkomBRzR821xRn3YCKXC9E0948fzSsEk">

Thanks!!!
